//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TeleHelp.Interfaces
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConexaoViaEntityFW : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConexaoViaEntityFW object using the connection string found in the 'ConexaoViaEntityFW' section of the application configuration file.
        /// </summary>
        public ConexaoViaEntityFW() : base("name=ConexaoViaEntityFW", "ConexaoViaEntityFW")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConexaoViaEntityFW object.
        /// </summary>
        public ConexaoViaEntityFW(string connectionString) : base(connectionString, "ConexaoViaEntityFW")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConexaoViaEntityFW object.
        /// </summary>
        public ConexaoViaEntityFW(EntityConnection connection) : base(connection, "ConexaoViaEntityFW")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SISCadastroFuncionario> SISCadastroFuncionarios
        {
            get
            {
                if ((_SISCadastroFuncionarios == null))
                {
                    _SISCadastroFuncionarios = base.CreateObjectSet<SISCadastroFuncionario>("SISCadastroFuncionarios");
                }
                return _SISCadastroFuncionarios;
            }
        }
        private ObjectSet<SISCadastroFuncionario> _SISCadastroFuncionarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SISCadastroFuncionarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSISCadastroFuncionarios(SISCadastroFuncionario sISCadastroFuncionario)
        {
            base.AddObject("SISCadastroFuncionarios", sISCadastroFuncionario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelTeleHelpCadFunEF", Name="SISCadastroFuncionario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SISCadastroFuncionario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SISCadastroFuncionario object.
        /// </summary>
        /// <param name="idFuncionario">Initial value of the IdFuncionario property.</param>
        /// <param name="senhaFuncionario">Initial value of the SenhaFuncionario property.</param>
        /// <param name="dataInclusao">Initial value of the DataInclusao property.</param>
        /// <param name="flagAdmin">Initial value of the FlagAdmin property.</param>
        public static SISCadastroFuncionario CreateSISCadastroFuncionario(global::System.Int32 idFuncionario, global::System.String senhaFuncionario, global::System.DateTime dataInclusao, global::System.Boolean flagAdmin)
        {
            SISCadastroFuncionario sISCadastroFuncionario = new SISCadastroFuncionario();
            sISCadastroFuncionario.IdFuncionario = idFuncionario;
            sISCadastroFuncionario.SenhaFuncionario = senhaFuncionario;
            sISCadastroFuncionario.DataInclusao = dataInclusao;
            sISCadastroFuncionario.FlagAdmin = flagAdmin;
            return sISCadastroFuncionario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFuncionario
        {
            get
            {
                return _IdFuncionario;
            }
            set
            {
                if (_IdFuncionario != value)
                {
                    OnIdFuncionarioChanging(value);
                    ReportPropertyChanging("IdFuncionario");
                    _IdFuncionario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdFuncionario");
                    OnIdFuncionarioChanged();
                }
            }
        }
        private global::System.Int32 _IdFuncionario;
        partial void OnIdFuncionarioChanging(global::System.Int32 value);
        partial void OnIdFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeFuncionario
        {
            get
            {
                return _NomeFuncionario;
            }
            set
            {
                OnNomeFuncionarioChanging(value);
                ReportPropertyChanging("NomeFuncionario");
                _NomeFuncionario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeFuncionario");
                OnNomeFuncionarioChanged();
            }
        }
        private global::System.String _NomeFuncionario;
        partial void OnNomeFuncionarioChanging(global::System.String value);
        partial void OnNomeFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SenhaFuncionario
        {
            get
            {
                return _SenhaFuncionario;
            }
            set
            {
                OnSenhaFuncionarioChanging(value);
                ReportPropertyChanging("SenhaFuncionario");
                _SenhaFuncionario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SenhaFuncionario");
                OnSenhaFuncionarioChanged();
            }
        }
        private global::System.String _SenhaFuncionario;
        partial void OnSenhaFuncionarioChanging(global::System.String value);
        partial void OnSenhaFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtNascFuncionario
        {
            get
            {
                return _DtNascFuncionario;
            }
            set
            {
                OnDtNascFuncionarioChanging(value);
                ReportPropertyChanging("DtNascFuncionario");
                _DtNascFuncionario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtNascFuncionario");
                OnDtNascFuncionarioChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtNascFuncionario;
        partial void OnDtNascFuncionarioChanging(Nullable<global::System.DateTime> value);
        partial void OnDtNascFuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Idade
        {
            get
            {
                return _Idade;
            }
            set
            {
                OnIdadeChanging(value);
                ReportPropertyChanging("Idade");
                _Idade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Idade");
                OnIdadeChanged();
            }
        }
        private Nullable<global::System.Int32> _Idade;
        partial void OnIdadeChanging(Nullable<global::System.Int32> value);
        partial void OnIdadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cargo
        {
            get
            {
                return _Cargo;
            }
            set
            {
                OnCargoChanging(value);
                ReportPropertyChanging("Cargo");
                _Cargo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cargo");
                OnCargoChanged();
            }
        }
        private global::System.String _Cargo;
        partial void OnCargoChanging(global::System.String value);
        partial void OnCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInclusao
        {
            get
            {
                return _DataInclusao;
            }
            set
            {
                OnDataInclusaoChanging(value);
                ReportPropertyChanging("DataInclusao");
                _DataInclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInclusao");
                OnDataInclusaoChanged();
            }
        }
        private global::System.DateTime _DataInclusao;
        partial void OnDataInclusaoChanging(global::System.DateTime value);
        partial void OnDataInclusaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FlagAdmin
        {
            get
            {
                return _FlagAdmin;
            }
            set
            {
                OnFlagAdminChanging(value);
                ReportPropertyChanging("FlagAdmin");
                _FlagAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlagAdmin");
                OnFlagAdminChanged();
            }
        }
        private global::System.Boolean _FlagAdmin;
        partial void OnFlagAdminChanging(global::System.Boolean value);
        partial void OnFlagAdminChanged();

        #endregion

    
    }

    #endregion

    
}
